// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtgyw5mR3WxkhdKOwQ3EYPaWzV9hAc2V0',
    appId: '1:639982617371:web:5635cfb698f1a2ce6789be',
    messagingSenderId: '639982617371',
    projectId: 'tasky-app-f6134',
    authDomain: 'tasky-app-f6134.firebaseapp.com',
    storageBucket: 'tasky-app-f6134.firebasestorage.app',
    measurementId: 'G-T21L4NS8N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFKfRLMWthefpeo8w8vFiGl3z4YUoIkDE',
    appId: '1:639982617371:android:e4490f3d764d59ac6789be',
    messagingSenderId: '639982617371',
    projectId: 'tasky-app-f6134',
    storageBucket: 'tasky-app-f6134.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQJQvS1Domt00LHFlrtj5-tPjeS2eWGac',
    appId: '1:639982617371:ios:60728b7956a3b0b46789be',
    messagingSenderId: '639982617371',
    projectId: 'tasky-app-f6134',
    storageBucket: 'tasky-app-f6134.firebasestorage.app',
    iosBundleId: 'com.example.taskyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQJQvS1Domt00LHFlrtj5-tPjeS2eWGac',
    appId: '1:639982617371:ios:60728b7956a3b0b46789be',
    messagingSenderId: '639982617371',
    projectId: 'tasky-app-f6134',
    storageBucket: 'tasky-app-f6134.firebasestorage.app',
    iosBundleId: 'com.example.taskyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtgyw5mR3WxkhdKOwQ3EYPaWzV9hAc2V0',
    appId: '1:639982617371:web:fac1d93ef4ff057a6789be',
    messagingSenderId: '639982617371',
    projectId: 'tasky-app-f6134',
    authDomain: 'tasky-app-f6134.firebaseapp.com',
    storageBucket: 'tasky-app-f6134.firebasestorage.app',
    measurementId: 'G-9VB9934YMP',
  );
}
